### ISSUE TITLE
Report is not generated successfully

### ISSUE THREAD

**Issue by za** [StanGirard/yatas-markdown#14]
Hi there,

I've enabled the report plugin `.yatas.yml`:

```
plugins:
  - name: "aws"
    enabled: true
    source: "github.com/padok-team/yatas-aws"
    version: "latest"
    description: "Check for AWS good practices"
    exclude:
     # - AWS_S3_001
    include:
     # - "AWS_VPC_004"
     # - "AWS_VPC_003"
  - name: "markdown"
    enabled: true
    source: "github.com/padok-team/yatas-markdown"
    version: "latest"
    description: "Generates a markdown report"
```

And after I run `yatas`, I can only see this on `report.md`:
```
# Yatas 
```

Is there a way to debug this?

cc: @StanGirard
